### ISSUE TITLE
Example of how to use library

### ISSUE THREAD

**Issue by luke-hawk** [iamtheburd/lazy-cartesian-product#1]
Hey @iamtheburd, 
this is exactly what I was searching for all day, cheers! 
Do you mind adding an example snippet of how to use the library to the README? I'm kind of struggeling to get it running (I must admit that I'm fairly new to C++ though)

**Comment by iamtheburd** [comment]
Sure thing! I'll add a section to the README as soon as possible. In the meanwhile, take a look at my other repo, [combigen](https://github.com/iamtheburd/combigen), and you can see some of the ways I used the library (:

**Comment by iamtheburd** [comment]
I updated the README to show some of the examples, this provides a more straight-forward view than digging through the source code of the `combigen` program.
